spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: ${MONGO_CLUSTER_URI}
      database: basket

server:
  port: 8083
