spring:
  application:
    name: basket-consumer-ws
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: ${MONGO_CLUSTER_URI}
      database: basket

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
